### ISSUE TITLE
 PAT env variable  name is wrong in Samples.md 

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-devops-cli-extension#692]
1. PAT is picked from AZURE_DEVOPS_EXT_PAT not AZURE_DEVOPS_CLI_PAT
1. Step below can be removed from sample yaml if we just add Environment variable in the script running the actual command
 ```
- script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'
```

Change the step-
```
- script: |
    az pipelines build list
    git pr list
  displayName: 'Show build list and PRs'
```

To 

```
- script: |
    az pipelines build list
    git pr list
  displayName: 'Show build list and PRs'
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
```
