### ISSUE TITLE
Using devops commands in Azure Pipelines

### ISSUE THREAD

**Issue by elderrollins** [Azure/azure-devops-cli-extension#693]
**Describe the bug**
The powershell plugin inside azure devops won't run "az devops project create". It keeps telling me there's an authentication error. I have logged in previously and run the "az pipelines create" command and that works just fine. 

**To Reproduce**
create an azure devops multistage pipeline similar to this one. (using the azure cli won't work)
[---------------------------------------------------------------------------------------------------------]
# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'az extension add --name azure-devops; 
"$PAT" | az devops login --organization https://dev.azure.com/<Your Org>;
az devops project create --name "<A Project Name>" --organization https://dev.azure.com/<Your Org>'

[---------------------------------------------------------------------------------------------------------]

 
Azure-Devops extension version:  
azure-cli                         2.0.64 *

1. login to azure devops
2. create a new pipeline
3. replace the hello world code in the .yml with the code above

**Expected behavior**
I should be able to create an azure devops project with this command using the powershell plugin.

![image](https://user-images.githubusercontent.com/48522903/60057682-a9d9c380-96a2-11e9-8383-dd4775ca5f75.png)

**Comment by atbagga** [comment]
@elderrollins The following works for me which has minor changes compared to yours like 'echo' in the command and mostly formatting  which might have messed up when you copy pasted yml to this issue. 

In your script I would expect the log of command ```"$PAT" | az devops login --organization https://dev.azure.com/;``` failing first before the create project failure log which you posted, so it is hard to comment on what went wrong in your case.

```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      az extension add --name azure-devops 
      echo $(PAT) | az devops login --organization https://dev.azure.com/testorg
      az devops project create --name test12345 --organization https://dev.azure.com/testorg
```

But I suggest you should prefer this route of environment variable compared to piped login. If the Environment variable is set as below you should be able to run commands without running the login command explicitly.

```
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script:
      az extension add --name azure-devops
      az devops project create --name "test1234" --organization https://dev.azure.com/testorg
  env:
    AZURE_DEVOPS_EXT_PAT: $(PAT)
```

This is NOT a bug. I will wait for your response before closing the issue. 

Hope this helps!
